import test from 'node:test';import assert from 'node:assert/strict';import {startMedia,getMedia,recoverMedia} from '../src/xpace-media.mjs';
class Bucket{map=new Map();n=0;async get(k){const value=this.map.get(k);return value?{etag:value.etag,json:async()=>JSON.parse(value.body),body:value.body}:null;}async put(k,body,opts={}){const prior=this.map.get(k),cond=opts.onlyIf;if(cond?.etagDoesNotMatch==='*'&&prior)return null;if(cond?.etagMatches&&prior?.etag!==cond.etagMatches)return null;const value={body,etag:String(++this.n)};this.map.set(k,value);return value;}async delete(k){this.map.delete(k);}async list({prefix,limit=100}){return {objects:[...this.map.keys()].filter(k=>k.startsWith(prefix)).slice(0,limit).map(key=>({key}))};}}
const input=(kind='image')=>({kind,text:'Café recién hecho',language:'es',voice:'female',owner:'a'.repeat(64),requestId:crypto.randomUUID()});
const environment=()=>({STOCK_BUCKET:new Bucket(),NOTIFY_KEY:'fixture',ADMIRANEXT_INGEST_TOKEN:'ingest-fixture'});
function dependencies(){const counts={image:0,audio:0,video:0,poll:0,publish:0},published=[];const deps={image:async()=>{counts.image++;return Response.json({ok:true,b64:btoa('image-bytes'),mime:'image/jpeg'});},audio:async()=>{counts.audio++;return new Response('audio-bytes');},video:async req=>{counts.video++;const {prompt,...settings}=await req.json();assert.deepEqual(settings,{duration:8,aspect_ratio:'16:9',resolution:'720p'});assert.ok(prompt.startsWith('Crea un vídeo publicitario para una tienda. Cualquier voz o texto visible debe estar en castellano de España. Café recién hecho'));assert.match(prompt,/finished video itself/);return Response.json({request_id:'provider-video-123'});},poll:async()=>{counts.poll++;return Response.json({status:'done',video:{url:'https://vidgen.x.ai/test.mp4'}});},publish:async req=>{counts.publish++;published.push(await req.json());return Response.json({ok:true,id:'stock-fixture',num:777,url:'https://api.admira.store/stock/asset/stock-fixture',contentHash:'f'.repeat(64)});}};return {counts,deps,published};}
test('validation rejects arbitrary ownership, invalid IDs and unsupported inputs before paid calls',async()=>{const env=environment(),{deps,counts}=dependencies();for(const patch of [{owner:'mail@example.com'},{requestId:'provider-id'},{kind:'constructor'},{text:'x'.repeat(1501)},{language:'fr'}])assert.equal((await startMedia(env,{...input(),...patch},undefined,deps)).status,400);assert.equal(counts.image,0);});
test('image archive is hashed, retries do not pay twice, operation conflicts are visible and ownership stays private',async()=>{const env=environment(),data=input(),{deps,counts,published}=dependencies();const first=await(await startMedia(env,data,undefined,deps)).json();assert.equal(first.job.status,'done');assert.equal(first.job.stock.id,'stock-fixture');assert.equal(first.job.owner,undefined);assert.equal(first.job.text,undefined);assert.match(published[0].contentHash,/^[a-f0-9]{64}$/);assert.deepEqual(published[0].tags,['xpaceos','admira-xp','creatividad','es']);await startMedia(env,data,undefined,deps);await getMedia(env,data,undefined,deps);assert.equal(counts.image,1);assert.equal(counts.publish,1);assert.equal((await startMedia(env,{...data,text:'Different'},undefined,deps)).status,409);assert.equal((await getMedia(env,{...data,owner:'b'.repeat(64)},undefined,deps)).status,404);});
test('simultaneous retry sees a durable pending job and makes only one provider request',async()=>{const env=environment(),data=input(),{deps,counts}=dependencies();let release;deps.image=async()=>{counts.image++;await new Promise(resolve=>release=resolve);return Response.json({ok:true,b64:btoa('bytes')});};const first=startMedia(env,data,undefined,deps);while(!release)await new Promise(r=>setTimeout(r,1));const retry=await startMedia(env,data,undefined,deps);assert.equal(retry.status,202);assert.equal((await retry.json()).job.status,'generating');release();await first;assert.equal(counts.image,1);});
test('failed Stock save is retried without regenerating the audio',async()=>{const env=environment(),data=input('audio'),{deps,counts,published}=dependencies();const publish=deps.publish;deps.publish=async()=>new Response('unavailable',{status:503});const first=await(await startMedia(env,data,undefined,deps)).json();assert.equal(first.job.status,'archiving');assert.equal(counts.audio,1);deps.publish=publish;const recovered=await(await getMedia(env,data,undefined,deps)).json();assert.equal(recovered.job.status,'done');assert.equal(counts.audio,1);assert.equal(published[0].type,'locucion');assert.equal(published[0].motor,'elevenlabs-v4');});
test('cron completes and archives video without an open browser, with stable ingest identity',async()=>{const env=environment(),data=input('video'),{deps,counts,published}=dependencies();const first=await(await startMedia(env,data,undefined,deps)).json();assert.equal(first.job.status,'pending');assert.equal(first.job.providerId,undefined);await recoverMedia(env,undefined,deps);const done=await(await getMedia(env,data,undefined,deps)).json();assert.equal(done.job.status,'done');assert.equal(counts.video,1);assert.equal(counts.publish,1);assert.match(published[0].externalId,/^xpaceos:video:[a-f0-9]{64}$/);assert.equal((await env.STOCK_BUCKET.list({prefix:'xpace-pending/'})).objects.length,0);});
test('unsafe provider output and provider failures never publish an asset',async()=>{for(const output of [{status:'done',video:{url:'https://other.example/video.mp4'}},{status:'failed'}]){const env=environment(),data=input('video'),{deps,counts}=dependencies();deps.poll=async()=>Response.json(output);await startMedia(env,data,undefined,deps);const job=await(await getMedia(env,data,undefined,deps)).json();assert.equal(job.job.status,'failed');assert.equal(counts.publish,0);assert.equal(counts.video,1);}});

const {stockPublishHandler}=await import('../src/index.js');
test('committed Stock receipt does not wait for catalogue statistics or notifications',async()=>{
 const env=environment();let releaseStats;const originalGet=env.STOCK_BUCKET.get.bind(env.STOCK_BUCKET);
 env.STOCK_BUCKET.get=async key=>key==='stats/plays.json'?await new Promise(resolve=>releaseStats=()=>resolve(null)):originalGet(key);
 const background=[];const response=await Promise.race([stockPublishHandler(new Request('https://api.admira.store/stock/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'image',motor:'unit-fixture',base64:btoa('image-fixture'),mime:'image/jpeg',title:'fixture',tags:['unit-fixture']})}),env,{waitUntil(work){background.push(Promise.resolve(work).catch(()=>{}));}}),new Promise((_,reject)=>{const timer=setTimeout(()=>reject(Error('receipt waited for stats')),1000);timer.unref();})]);
 const receipt=await response.json();assert.equal(receipt.ok,true);assert.ok(await originalGet('stock/'+receipt.id+'/meta.json'));assert.ok(releaseStats);releaseStats();
});
test('ten-second image video preserves Stock provenance and retries never regenerate',async()=>{const env=environment(),data={...input('video'),imageId:'1791227596031-5ano5x',duration:10,aspect:'9:16'},{deps,counts,published}=dependencies();deps.video=async(req,_env,options)=>{counts.video++;const body=await req.json();assert.equal(body.stock_id,data.imageId);assert.equal(body.duration,10);assert.equal(body.aspect_ratio,'9:16');assert.match(body.prompt,/Conserva identidad/);assert.deepEqual(options,{imageDuration:10});return Response.json({request_id:'image-provider'});};const first=await(await startMedia(env,data,undefined,deps)).json();assert.equal(first.job.duration,10);assert.equal(first.job.sourceImageId,data.imageId);assert.equal(first.job.aspect,'9:16');await startMedia(env,data,undefined,deps);const final=await(await getMedia(env,data,undefined,deps)).json();assert.equal(final.job.status,'done');assert.equal(counts.video,1);assert.match(published[0].comment,/10 s · 9:16/);assert.match(published[0].comment,/1791227596031-5ano5x/);assert.equal((await startMedia(env,{...data,imageId:'another-source'},undefined,deps)).status,409);assert.equal((await startMedia(env,{...data,aspect:'16:9'},undefined,deps)).status,409);});
test('private image route sends the original pixels with ten seconds while public five-second contract stays',async()=>{const {xaiVideoStartHandler}=await import('../src/index.js');const original=globalThis.fetch;let payload,calls=0;globalThis.fetch=async(_url,options)=>{calls++;payload=JSON.parse(options.body);return Response.json({request_id:'private-image-10'});};const env={XAI_KEY:'fixture',STOCK_BUCKET:{get:async key=>key.endsWith('meta.json')?{json:async()=>({assetKey:'stock/image-123/asset.png',mime:'image/png'})}:{arrayBuffer:async()=>new Uint8Array([137,80,78,71]).buffer,httpMetadata:{contentType:'image/png'}}}};const request=()=>new Request('https://api.admira.store/xai/video',{method:'POST',body:JSON.stringify({prompt:'Expand product details',stock_id:'image-123',duration:10,aspect_ratio:'9:16'})});try{assert.equal((await xaiVideoStartHandler(request(),env,{imageDuration:10})).status,200);assert.equal(payload.duration,10);assert.equal(payload.aspect_ratio,'9:16');assert.match(payload.image.url,/^data:image\/png;base64,/);assert.equal((await xaiVideoStartHandler(request(),env)).status,400);assert.equal(calls,1);}finally{globalThis.fetch=original;}});
test('backend video jobs keep language and image provenance while requesting final artwork without accidental display hardware',async()=>{
 for(const data of [{...input('video'),text:'Café para pantalla 9:16'},{...input('video'),language:'en',text:'Photographed screen installation inside a store',imageId:'source-image',duration:10,aspect:'9:16'}]){
  const env=environment(),{deps}=dependencies();let body,options;
  deps.video=async(req,_env,opts)=>{body=await req.json();options=opts;return Response.json({request_id:'fixture'});};
  const result=await(await startMedia(env,data,undefined,deps)).json();assert.equal(result.job.status,'pending');
  assert.ok(body.prompt.includes(data.text));assert.match(body.prompt,/finished video itself/);assert.match(body.prompt,/canvas edge to edge/);
  assert.match(body.prompt,/not an object to photograph/);assert.match(body.prompt,/explicitly asks for a mockup or photographed installation/);
  if(data.imageId){assert.match(body.prompt,/visible text must be in English/);assert.match(body.prompt,/Preserve identity, existing text, prices and claims/);assert.equal(body.stock_id,data.imageId);assert.equal(body.duration,10);assert.equal(body.aspect_ratio,'9:16');assert.deepEqual(options,{imageDuration:10});}
  else{assert.match(body.prompt,/castellano de España/);assert.equal(body.duration,8);assert.equal(body.stock_id,undefined);}
 }
});
