import test from 'node:test';import assert from 'node:assert/strict';import {startMedia,getMedia,recoverMedia} from '../src/xpace-media.mjs';
class Bucket{map=new Map();n=0;async get(k){const value=this.map.get(k);return value?{etag:value.etag,json:async()=>JSON.parse(value.body),body:value.body}:null;}async put(k,body,opts={}){const prior=this.map.get(k),cond=opts.onlyIf;if(cond?.etagDoesNotMatch==='*'&&prior)return null;if(cond?.etagMatches&&prior?.etag!==cond.etagMatches)return null;const value={body,etag:String(++this.n)};this.map.set(k,value);return value;}async delete(k){this.map.delete(k);}async list({prefix,limit=100}){return {objects:[...this.map.keys()].filter(k=>k.startsWith(prefix)).slice(0,limit).map(key=>({key}))};}}
const input=(kind='image')=>({kind,text:'Café recién hecho',language:'es',voice:'female',owner:'a'.repeat(64),requestId:crypto.randomUUID()});
const environment=()=>({STOCK_BUCKET:new Bucket(),NOTIFY_KEY:'fixture',ADMIRANEXT_INGEST_TOKEN:'ingest-fixture'});
function dependencies(){const counts={image:0,audio:0,video:0,poll:0,publish:0},published=[];const deps={image:async()=>{counts.image++;return Response.json({ok:true,b64:btoa('image-bytes'),mime:'image/jpeg'});},audio:async()=>{counts.audio++;return new Response('audio-bytes');},video:async req=>{counts.video++;assert.deepEqual(await req.json(),{prompt:'Crea un vídeo publicitario para una tienda. Cualquier voz o texto visible debe estar en castellano de España. Café recién hecho',duration:8,aspect_ratio:'16:9',resolution:'720p'});return Response.json({request_id:'provider-video-123'});},poll:async()=>{counts.poll++;return Response.json({status:'done',video:{url:'https://vidgen.x.ai/test.mp4'}});},publish:async req=>{counts.publish++;published.push(await req.json());return Response.json({ok:true,id:'stock-fixture',num:777,url:'https://api.admira.store/stock/asset/stock-fixture',contentHash:'f'.repeat(64)});}};return {counts,deps,published};}
test('validation rejects arbitrary ownership, invalid IDs and unsupported inputs before paid calls',async()=>{const env=environment(),{deps,counts}=dependencies();for(const patch of [{owner:'mail@example.com'},{requestId:'provider-id'},{kind:'constructor'},{text:'x'.repeat(1501)},{language:'fr'}])assert.equal((await startMedia(env,{...input(),...patch},undefined,deps)).status,400);assert.equal(counts.image,0);});
test('image archive is hashed, retries do not pay twice, operation conflicts are visible and ownership stays private',async()=>{const env=environment(),data=input(),{deps,counts,published}=dependencies();const first=await(await startMedia(env,data,undefined,deps)).json();assert.equal(first.job.status,'done');assert.equal(first.job.stock.id,'stock-fixture');assert.equal(first.job.owner,undefined);assert.equal(first.job.text,undefined);assert.match(published[0].contentHash,/^[a-f0-9]{64}$/);assert.deepEqual(published[0].tags,['xpaceos','admira-xp','creatividad','es']);await startMedia(env,data,undefined,deps);await getMedia(env,data,undefined,deps);assert.equal(counts.image,1);assert.equal(counts.publish,1);assert.equal((await startMedia(env,{...data,text:'Different'},undefined,deps)).status,409);assert.equal((await getMedia(env,{...data,owner:'b'.repeat(64)},undefined,deps)).status,404);});
test('simultaneous retry sees a durable pending job and makes only one provider request',async()=>{const env=environment(),data=input(),{deps,counts}=dependencies();let release;deps.image=async()=>{counts.image++;await new Promise(resolve=>release=resolve);return Response.json({ok:true,b64:btoa('bytes')});};const first=startMedia(env,data,undefined,deps);while(!release)await new Promise(r=>setTimeout(r,1));const retry=await startMedia(env,data,undefined,deps);assert.equal(retry.status,202);assert.equal((await retry.json()).job.status,'generating');release();await first;assert.equal(counts.image,1);});
test('failed Stock save is retried without regenerating the audio',async()=>{const env=environment(),data=input('audio'),{deps,counts,published}=dependencies();const publish=deps.publish;deps.publish=async()=>new Response('unavailable',{status:503});const first=await(await startMedia(env,data,undefined,deps)).json();assert.equal(first.job.status,'archiving');assert.equal(counts.audio,1);deps.publish=publish;const recovered=await(await getMedia(env,data,undefined,deps)).json();assert.equal(recovered.job.status,'done');assert.equal(counts.audio,1);assert.equal(published[0].type,'locucion');assert.equal(published[0].motor,'elevenlabs-v4');});
test('cron completes and archives video without an open browser, with stable ingest identity',async()=>{const env=environment(),data=input('video'),{deps,counts,published}=dependencies();const first=await(await startMedia(env,data,undefined,deps)).json();assert.equal(first.job.status,'pending');assert.equal(first.job.providerId,undefined);await recoverMedia(env,undefined,deps);const done=await(await getMedia(env,data,undefined,deps)).json();assert.equal(done.job.status,'done');assert.equal(counts.video,1);assert.equal(counts.publish,1);assert.match(published[0].externalId,/^xpaceos:video:[a-f0-9]{64}$/);assert.equal((await env.STOCK_BUCKET.list({prefix:'xpace-pending/'})).objects.length,0);});
test('unsafe provider output and provider failures never publish an asset',async()=>{for(const output of [{status:'done',video:{url:'https://other.example/video.mp4'}},{status:'failed'}]){const env=environment(),data=input('video'),{deps,counts}=dependencies();deps.poll=async()=>Response.json(output);await startMedia(env,data,undefined,deps);const job=await(await getMedia(env,data,undefined,deps)).json();assert.equal(job.job.status,'failed');assert.equal(counts.publish,0);assert.equal(counts.video,1);}});
